# Define stages for the pipeline
stages:
  - ci
  - deploy

# Use the official Ruby 4.0.1 image
image: ruby:4.0.1

# This is your main test job
backend_ci:
  stage: ci
  variables:
    RAILS_ENV: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - backend/**/*
  before_script:
    - apt-get update -qq && apt-get install -y libsqlite3-dev
    - cd backend
    - bundle install
    - bin/rails db:test:prepare
  script:
    - bin/ci

backend_deploy:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - backend/**/*
        - .gitlab-ci.yml
        - railway.toml
  script:
    - railway up --service digital-training-log-api --ci

frontend_deploy:
  stage: deploy
  image: node:22-alpine
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - frontend/**/*
        - .gitlab-ci.yml
        - netlify.toml
  variables:
    COREPACK_HOME: ".corepack"
  script:
    - apk add --no-cache libc6-compat
    - corepack enable
    - corepack prepare yarn@4.12.0 --activate
    - npm install -g netlify-cli
    - cd frontend
    - yarn install --immutable
    - yarn build
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=dist
