# Define stages for the pipeline
stages:
  - ci
  - deploy

# Use the official Ruby 4.0.1 image
image: ruby:4.0.1

# This is your main test job
backend_ci:
  stage: ci
  variables:
    RAILS_ENV: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - backend/**/*
  before_script:
    - apt-get update -qq && apt-get install -y libsqlite3-dev
    - cd backend
    - bundle install
    - bin/rails db:test:prepare
  script:
    - bin/ci

backend_deploy:
  stage: deploy
  image: ubuntu:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service digital-training-log-api -t $RAILWAY_TOKEN --ci
